// Predefined bet templates per category
export const BET_TEMPLATES = {
  fitness: [
    { titleRu: 'Бегать каждый день',     titleEn: 'Run every day',               proof_type: 'steps_km', icon: '🏃' },
    { titleRu: 'Пройти 10 000 шагов',    titleEn: 'Walk 10,000 steps',           proof_type: 'steps_km', icon: '👟' },
    { titleRu: 'Тренировка 3 раза в нед',titleEn: 'Workout 3 times a week',      proof_type: 'photo',    icon: '💪' },
    { titleRu: 'Отжиматься каждый день', titleEn: 'Do push-ups every day',       proof_type: 'photo',    icon: '🤸' },
    { titleRu: 'Подтягиваться каждый день', titleEn: 'Do pull-ups every day',    proof_type: 'photo',    icon: '🏋️' },
    { titleRu: 'Плавание 2 раза в нед',  titleEn: 'Swim twice a week',           proof_type: 'photo',    icon: '🏊' },
    { titleRu: 'Езда на велосипеде',     titleEn: 'Cycle daily',                 proof_type: 'steps_km', icon: '🚴' },
    { titleRu: 'Утренняя зарядка',       titleEn: 'Morning workout',             proof_type: 'photo',    icon: '🌅' },
  ],
  health: [
    { titleRu: 'Не есть сладкое',        titleEn: 'No sweets',                   proof_type: 'any',      icon: '🚫🍬' },
    { titleRu: 'Пить 2л воды в день',    titleEn: 'Drink 2L water daily',        proof_type: 'photo',    icon: '💧' },
    { titleRu: 'Не пить алкоголь',       titleEn: 'No alcohol',                  proof_type: 'any',      icon: '🚫🍺' },
    { titleRu: 'Ложиться спать до 23:00',titleEn: 'Sleep before 11pm',           proof_type: 'photo',    icon: '😴' },
    { titleRu: 'Правильное питание',     titleEn: 'Eat healthy',                 proof_type: 'photo',    icon: '🥗' },
    { titleRu: 'Не есть фастфуд',        titleEn: 'No fast food',               proof_type: 'any',      icon: '🚫🍔' },
    { titleRu: 'Витамины каждый день',   titleEn: 'Take vitamins daily',         proof_type: 'photo',    icon: '💊' },
    { titleRu: 'Медитация 10 мин',       titleEn: 'Meditate 10 min daily',       proof_type: 'photo',    icon: '🧘' },
  ],
  learning: [
    { titleRu: 'Учить английский 30 мин',titleEn: 'Study English 30 min/day',    proof_type: 'photo',    icon: '🇬🇧' },
    { titleRu: 'Читать каждый день',     titleEn: 'Read every day',              proof_type: 'photo',    icon: '📚' },
    { titleRu: 'Пройти онлайн-курс',     titleEn: 'Complete an online course',   proof_type: 'photo',    icon: '💻' },
    { titleRu: 'Учить новые слова',      titleEn: 'Learn new vocabulary daily',  proof_type: 'photo',    icon: '📖' },
    { titleRu: 'Программировать 1 час',  titleEn: 'Code for 1 hour daily',       proof_type: 'photo',    icon: '⌨️' },
    { titleRu: 'Смотреть лекции',        titleEn: 'Watch educational videos',    proof_type: 'photo',    icon: '🎓' },
    { titleRu: 'Изучить новый язык',     titleEn: 'Study a new language',        proof_type: 'photo',    icon: '🌍' },
    { titleRu: 'Практиковать навык',     titleEn: 'Practice a skill daily',      proof_type: 'photo',    icon: '🎯' },
  ],
  productivity: [
    { titleRu: 'Не сидеть в соцсетях',  titleEn: 'No social media',             proof_type: 'any',      icon: '📵' },
    { titleRu: 'Вставать в 6 утра',      titleEn: 'Wake up at 6am',             proof_type: 'photo',    icon: '⏰' },
    { titleRu: 'Делать to-do list',      titleEn: 'Write a daily to-do list',    proof_type: 'photo',    icon: '✅' },
    { titleRu: 'Без прокрастинации',     titleEn: 'No procrastination day',      proof_type: 'any',      icon: '🎯' },
    { titleRu: 'Поработать 8 часов',     titleEn: 'Work 8 focused hours',        proof_type: 'photo',    icon: '💼' },
    { titleRu: 'Техника Помодоро',       titleEn: 'Use Pomodoro technique',      proof_type: 'photo',    icon: '🍅' },
    { titleRu: 'Без телефона до обеда',  titleEn: 'No phone before noon',        proof_type: 'any',      icon: '📱' },
    { titleRu: 'Завершать задачи вовремя',titleEn: 'Complete tasks on time',     proof_type: 'any',      icon: '⚡' },
  ],
  mindfulness: [
    { titleRu: 'Медитировать каждый день',titleEn: 'Meditate daily',             proof_type: 'photo',    icon: '🧘' },
    { titleRu: 'Вести дневник',           titleEn: 'Write in a journal',         proof_type: 'photo',    icon: '📔' },
    { titleRu: 'Практика благодарности', titleEn: 'Gratitude practice',          proof_type: 'photo',    icon: '🙏' },
    { titleRu: 'Дыхательные упражнения', titleEn: 'Breathing exercises',         proof_type: 'photo',    icon: '🫁' },
    { titleRu: 'Цифровой детокс',        titleEn: 'Digital detox hours',         proof_type: 'any',      icon: '🌿' },
    { titleRu: 'Прогулка на природе',    titleEn: 'Walk in nature daily',        proof_type: 'photo',    icon: '🌳' },
  ],
  finance: [
    { titleRu: 'Не тратить лишнее',      titleEn: 'No unnecessary spending',     proof_type: 'photo',    icon: '💰' },
    { titleRu: 'Откладывать деньги',     titleEn: 'Save money daily',            proof_type: 'photo',    icon: '🏦' },
    { titleRu: 'Вести бюджет',           titleEn: 'Track your budget',           proof_type: 'photo',    icon: '📊' },
    { titleRu: 'Не брать кредиты',       titleEn: 'No new loans/credits',        proof_type: 'any',      icon: '🚫' },
    { titleRu: 'Инвестировать',          titleEn: 'Make an investment',          proof_type: 'photo',    icon: '📈' },
    { titleRu: 'Без доставки еды',       titleEn: 'No food delivery',            proof_type: 'any',      icon: '🚫🚗' },
  ],
  social: [
    { titleRu: 'Звонить родителям',      titleEn: 'Call parents daily',          proof_type: 'any',      icon: '📞' },
    { titleRu: 'Познакомиться с кем-то', titleEn: 'Meet someone new',            proof_type: 'photo',    icon: '🤝' },
    { titleRu: 'Помогать другим',        titleEn: 'Help someone each day',       proof_type: 'any',      icon: '❤️' },
    { titleRu: 'Без конфликтов',         titleEn: 'No conflicts',                proof_type: 'any',      icon: '☮️' },
    { titleRu: 'Проводить время с семьёй',titleEn: 'Quality time with family',   proof_type: 'photo',    icon: '👨👩👧' },
    { titleRu: 'Отвечать на сообщения',  titleEn: 'Reply to all messages',       proof_type: 'any',      icon: '💬' },
  ],
  custom: [], // user writes their own
};